###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2020. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
# IBM Corporation - initial API and implementation
###############################################################################
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cfmr-operator
  labels:
    app.kubernetes.io/instance: cfmr-instance
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: cfmr-operator
    release: cfmr-operator
subjects:
- kind: ServiceAccount
  name: cfmr-operator
  namespace: cfmr-operator
roleRef:
  kind: ClusterRole
  name: cfmr-operator
  apiGroup: rbac.authorization.k8s.io
