###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2020. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
# IBM Corporation - initial API and implementation
###############################################################################
apiVersion: cfmr.ibm.com/v2
kind: IbmCfmrProd
metadata:
  name: airgap-four-seven
  namespace: cfmr-operator
  labels:
    release: cfmr-operator
    app.kubernetes.io/name: cfmr-operator
    app.kubernetes.io/instance: cfmr-instance
    app.kubernetes.io/managed-by: helm
spec:
  action: install
  features:
    cfmrVersion: 2.7.12
    cfoVersion: 7.1.3+0.g0ce050b
    embeddedDatabase:
      enabled: true
    enableCertManager: false
    enableHighAvailability: true
    externalDatabase:
      caCert: ""
      databases:
        bbs:
          name: diego
          password: ""
          username: ""
        cc:
          name: cloud_controller
          password: ""
          username: ""
        credhub:
          name: credhub
          password: ""
          username: ""
        locket:
          name: locket
          password: ""
          username: ""
        policyServer:
          name: network_policy
          password: ""
          username: ""
        routingApi:
          name: routing-api
          password: ""
          username: ""
        silkController:
          name: network_connectivity
          password: ""
          username: ""
        uaa:
          name: uaa
          password: ""
          username: ""
      enabled: false
      host: ""
      port: ""
      requireSSL: false
      type: ""
    ldap:
      attributes:
        id: ""
        name: ""
        preferredUsername: ""
      bindDN: ""
      bindPassword: ""
      ccAdminFilter: ""
      enableIntegration: false
      filterParams: ""
      groups:
        groupSearchFilter: ""
        maxSearchDepth: ""
        searchBase: ""
      ipAddress: ""
      port: ""
      searchBase: ""
      searchFilter: ""
      userDN: ""
      userPassword: ""
    multiEnvironments: ""
    stack: cflinuxfs3
    storageClass: ""
    stratosVersion: 4.4.0
    customDomain: "airgap.cfmr.site"
    customCertNamespace: "openshift-ingress"
    customCertSecret: "four-seven-luck-2025abf5e73a457f12bb6f6fae6f9c13-0000"
    chartRepository: "http://private-helm-repo-chartmuseum-private-helm-repo.four-seven-luck-2025abf5e73a457f12bb6f6fae6f9c13-0000.tor01.containers.appdomain.cloud"
    chartRepositoryName: "private-helm-repo"
    persiBrokerRWXstorageClass: ""
    persiBrokerRWOstorageClass: ""
  global:
    image:
      # Needs to be updated
      pullSecret: "prod-entitled-registry"
      repository: ""
    podAnnotations:
      productID: c958f891c5764678aa38b173c4950f06
      productMetric: VIRTUAL_PROCESSOR_CORE
      productName: IBM Cloud Foundry Migration Runtime
      productVersion: "4.1.0"
      productChargedContainers: "All"
  image:
    pullPolicy: IfNotPresent
    repository: us.icr.io/boilerupnc/cfmr-installer
    tag: 1.3.1
    digest: sha256:294e970dfd335aae625716997e8d706bf0f54ddbf7d4f4fb61df4c8441b8cb4d
  license:
    # Change license to true to indicate you have read and agree to license agreements : http://ibm.biz/cfmr-license
    accept: true
  rbac:
    create: true
    existingServiceAccount: ""
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  
